---
- name: Install common packages
  hosts: all
  become: true
  tasks:
    -  include_tasks: tasks/common.yml

- name: Install and Configure Database
  hosts: lamp-db
  gather_facts: true
  become: true
  tasks:
    - include_tasks: tasks/db.yml

- name: Install and Configure Web Server
  hosts: lamp-web
  gather_facts: true
  become: true
  tasks:
    - include_tasks: tasks/web.yml
      