---
- name: Install common packages
  hosts: all
  become: true
  tasks:
    - name: Install common dependencies
      yum:
        name:
          - libselinux-python
          - libsemanage-python
          - firewalld
        state: installed

- name: Install and Configure Database
  hosts: lamp-db
  become: true
  tasks:
    - name: Install MariaDB package
      yum:
        name:
          - mariadb-server
          - MySQL-python
        state: installed

    - name: Create Mysql configuration file
      copy:
        src: files/my.cnf
        dest: /etc/my.cnf

    - name: Start MariaDB Service
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Start firewalld
      service:
        name: firewalld
        state: started
        enabled: true

    - name: insert firewalld rule
      firewalld:
        port: "{{ mysql_port }}/tcp"
        state: enabled
        permanent: true
        immediate: true

    - name: Create Application Database
      mysql_db:
        name: "{{ dbname }}"
        state: present

    - name: Create Application DB User
      mysql_user:
        name: "{{ dbuser }}"
        password: "{{ dbpassword }}"
        priv: "*.*:ALL"
        host: "{{ hostvars.lamp-web.ansible_host }}"
        state: present

    - name: Move db-load-script to db host
      copy:
        src: files/db-load-script.sql
        dest: /tmp/db-load-script.sql

    - name: Load Inventory Data
      shell: mysql -f < /tmp/db-load-script.sql